version: 2
updates:

    # Maintain dependecies for Gems
  - package-ecosystem: "bundler" 
    directory: "/" 
    schedule:
      interval: "weekly"
    
    # Allow update of all dependencies
    allow: 
      - dependency-type: "all"
      
    reviewers:
      - "danielmbrasil"
      - "Utzig26"
    
    commit-message: 
      prefix: "gems"
      include: "scope"
      
    labels:
      - "gems"
      - "dependencies"
      
    pull-request-branch-name:
      separator: "-"
